### ISSUE TITLE
Ошибки в бланке РедАдрес

### ISSUE THREAD

**Issue by shenaiya** [TB-Budget/AddressK#2]
Бланки/Справочники/РедАдрес опечатка в слове "Естественная запись".
Ошибка "Параметр задан не верно" при открытии бланка.

**Comment by Scondo** [comment]
Исправлено
https://github.com/TB-Budget/T9_XMLRPC/commit/23d331e459dcdfd35cd33bf0716508c520a9d0b9
https://github.com/TB-Budget/AddressK/commit/da0768420157c05b8b456e5a38757ae9b95a49d6
